# Generated by Django 5.0.3 on 2024-10-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_fooditem_delete_mother_ins_delete_mother_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ing',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ins',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='age',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='district',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='people_served',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
